services:
  veg-frontend:
    build:
      context: ./veg
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    env_file:
      - ./veg/.env.docker

  veg-backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    env_file:
      - ./server/.env.docker